src/java/indexController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.StringReader;
import java.util.ArrayList;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.json.Json;
import javax.json.JsonObject;
import org.scribe.model.OAuthRequest;
import org.scribe.model.Response;
import org.scribe.model.Verb;

/**
 *
 * @author bboybeam
 */
@ManagedBean
@RequestScoped
public class indexController {
    private String searchQuery = "";
    private ArrayList<Photo> photos;
    private ArrayList<Photo> searchedPhotos;
    private Photo p1;
    private Photo p2;
    private Photo p3;
    private Photo p4;
    private Photo p5;
    
    
    private static final String PROTECTED_RESOURCE_URL = "http://api.flickr.com/services/rest/?";
    /**
     * Creates a new instance of indexController
     */
    public indexController() {
        searchQuery = "";
    }

    public void setPhotos(ArrayList<Photo> photos) {
        this.photos = photos;
    }

    public ArrayList<Photo> getPhotos() {
        return photos;
    }

    public void setSearchedPhotos(ArrayList<Photo> searchPhotos) {
        this.searchedPhotos = searchPhotos;
    }

    public ArrayList<Photo> getSearchedPhotos() {
        return searchedPhotos;
    }
    

    
    /**
     * Return an array of recent photos.
     */
    public ArrayList<Photo> getRecentPhotos() {
        FlickrApp app = FlickrApp.getInstance();
        
        OAuthRequest request = new OAuthRequest(Verb.GET, PROTECTED_RESOURCE_URL);
        
        request.addQuerystringParameter("method", "flickr.photos.getRecent");
        request.addQuerystringParameter("api_key",FlickrApp.getApiKey());
        request.addQuerystringParameter("format", "json");
        request.addQuerystringParameter("nojsoncallback", "1");
        Response response = request.send();
        
        
        JsonObject json = Json.createReader(new StringReader(response.getBody())).readObject();
        
        JsonObject result = json.getJsonObject("photos");
        
        // Create a list to hold results (if any)
        photos = new ArrayList<Photo>();
        
        for (int i=0; i < 6; i++) {
            
            // Create a new photo object for each result
            JsonObject photoDetails = result.getJsonArray("photo").getJsonObject(i);
            
            // Get the required information needed
            String id = photoDetails.getString("id");
            String owner = photoDetails.getString("owner");
            String secret = photoDetails.getString("secret");
            String server = photoDetails.getString("server");
            int farm = photoDetails.getInt("farm");
            String title = photoDetails.getString("title");
            int ispublic = photoDetails.getInt("ispublic");
            int isfriend = photoDetails.getInt("isfriend");
            int isfamily = photoDetails.getInt("isfamily");

            // Create the Photo object
            Photo p = new Photo(id, owner, secret, server, farm, title, ispublic, isfriend, isfamily);
            
            // And add to our container
            photos.add(p);
        }
            p1 = photos.get(0);
            p2 = photos.get(1);
            p3 = photos.get(2);
            p4 = photos.get(3);
            p5 = photos.get(4);
            return photos;
    }
    
    
    /**
     * Return an array of photos based on user's query
     */
     public ArrayList<Photo> getSearchPhotos() {
         if (searchQuery.equals("")) {
            // Return blank arraylist if blank search query
            return new ArrayList<Photo>();
        }else {
        FlickrApp app = FlickrApp.getInstance();
        

        OAuthRequest request = new OAuthRequest(Verb.GET, PROTECTED_RESOURCE_URL);
        
        request.addQuerystringParameter("method", "flickr.photos.search");
        request.addQuerystringParameter("api_key",FlickrApp.getApiKey());
        request.addQuerystringParameter("text", searchQuery);
        request.addQuerystringParameter("format", "json");
        request.addQuerystringParameter("nojsoncallback", "1");
        Response response = request.send();

        
        JsonObject json = Json.createReader(new StringReader(response.getBody())).readObject();
        
        JsonObject result = json.getJsonObject("photos");
        int resultSize = result.getJsonArray("photo").size();
        
        // Create a list to hold results (if any)
        searchedPhotos = new ArrayList<Photo>();
        
        for (int i=0; i < resultSize; i++) {
            
            // Create a new photo object for each result
            JsonObject photoDetails = result.getJsonArray("photo").getJsonObject(i);
            
            // Get the required information needed
            String id = photoDetails.getString("id");
            String owner = photoDetails.getString("owner");
            String secret = photoDetails.getString("secret");
            String server = photoDetails.getString("server");
            int farm = photoDetails.getInt("farm");
            String title = photoDetails.getString("title");
            if(title.length() >= 20) {
                title = title.substring(0, 20);
            }
            int ispublic = photoDetails.getInt("ispublic");
            int isfriend = photoDetails.getInt("isfriend");
            int isfamily = photoDetails.getInt("isfamily");

            // Create the Photo object
            Photo p = new Photo(id, owner, secret, server, farm, title, ispublic, isfriend, isfamily);
            
            
            
            // And add to our container
            searchedPhotos.add(p);
        }
            return searchedPhotos;
        }
    }

    public void setSearchQuery(String searchQuery) {
        this.searchQuery = searchQuery;
    }
    
    public String getSearchQuery() {
        return searchQuery;
    }
    
    public Photo getP1() {
        return p1;
    }

    public Photo getP2() {
        return p2;
    }

    public Photo getP3() {
        return p3;
    }

    public Photo getP4() {
        return p4;
    }

    public Photo getP5() {
        return p5;
    }
    
    
}

src/java/placesController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.StringReader;
import java.util.ArrayList;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.json.Json;
import javax.json.JsonObject;
import org.scribe.model.OAuthRequest;
import org.scribe.model.Response;
import org.scribe.model.Verb;

/**
 *
 * @author bboybeam
 */
@ManagedBean
@RequestScoped
public class placesController {
    private ArrayList<Place> places;
    private Place place;
    private String searchQuery = "";
    private static final String PROTECTED_RESOURCE_URL = "http://api.flickr.com/services/rest/?";
    /**
     * Creates a new instance of placesController
     */
    public placesController() {
        searchQuery = "";
    }

    public void setPlaces(ArrayList<Place> places) {
        this.places = places;
    }

    
    /**
     * Return an array of places based on user's query
     */
    public ArrayList<Place> getPlaces() {
         if (searchQuery.equals("")) {
            // Return blank arraylist if blank search query
            return new ArrayList<Place>();
        }else {
        FlickrApp app = FlickrApp.getInstance();
        

        OAuthRequest request = new OAuthRequest(Verb.GET, PROTECTED_RESOURCE_URL);
        
        request.addQuerystringParameter("method", "flickr.places.find");
        request.addQuerystringParameter("api_key",FlickrApp.getApiKey());
        request.addQuerystringParameter("query", searchQuery);
        request.addQuerystringParameter("format", "json");
        request.addQuerystringParameter("nojsoncallback", "1");
        Response response = request.send();

        
        JsonObject json = Json.createReader(new StringReader(response.getBody())).readObject();
        
        JsonObject result = json.getJsonObject("places");
        
        // Create a list to hold results (if any)
        places = new ArrayList<Place>();     
        // Create a new photo object for each result
        JsonObject placeDetails = result.getJsonArray("place").getJsonObject(0);

        // Get the required information needed
        String placeid = placeDetails.getString("place_id");
        String woeid = placeDetails.getString("woeid");
        String latitude = placeDetails.getString("latitude");
        String longitude = placeDetails.getString("longitude");
        String placeUrl = placeDetails.getString("place_url");
        String placeType = placeDetails.getString("place_type");
        String placeTypeId = placeDetails.getString("place_type_id");
        String timezone = placeDetails.getString("timezone");
        String content = placeDetails.getString("_content");
        String woeName = placeDetails.getString("woe_name");
        
        // Create the Photo object
        Place p = new Place(placeid, woeid, latitude, longitude, placeUrl, placeType, placeTypeId, timezone, content, woeName);


        // And add to our container
        places.add(p);
        }
        place = places.get(0);
        return places;
    }

    public Place getPlace() {
        return place;
    }

    public String getSearchQuery() {
        return searchQuery;
    }

    public void setSearchQuery(String searchQuery) {
        this.searchQuery = searchQuery;
    }
    
    
}

web/author.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>People</title>
        <link rel="stylesheet" href="resources/css/jquery.fancybox.css" />
        <link rel="stylesheet" href="resources/css/jquery.fancybox-thumbs.css" />
        <link rel="stylesheet" href="resources/css/main.css" />
        <script type="text/javascript" src="resources/js/jquery-1.10.2.js"></script>
        <script type="text/javascript" src="resources/js/jquery.fancybox.pack.js"></script>
        <script type="text/javascript" src="resources/js/main.js"></script>
    </h:head>
    <h:body id="people">
        <div id="wrapper">
            <h:form>
            <div id="header">
                <h:link outcome="index"><img id="logo" src="resources/img/LOGO.png" alt="Flickr Photo Box" /></h:link>
                <!-- Navigation bar -->
                <div id="navbar">
                    <ul>
                        <li><h:link styleClass="navLink" outcome="index">Home</h:link></li>
                        <li><h:link styleClass="navLink" outcome="places">Places</h:link></li>
                        <li id="peopleNav"><h:link styleClass="navLink" outcome="author">People</h:link></li>
                    </ul>
                </div>
            </div>
            
            <div class="clear">
                <p></p>
            </div>
           <!-- Page main content, display the users, their recent photos and also show use's contacts -->
          <div id="content">
              <h:outputText style="display: none;" rendered="#{not empty indexController.recentPhotos}"></h:outputText>
              <ui:repeat  value="#{indexController.recentPhotos}" var="photo" varStatus="status">
                    <div class="authorDetailsSection">
                        <div class="authorPersonalInfo">
                            <img class="authorIcon" src="#{photo.photoUser.buddyIconUrl}"></img>
                            <h2>
                                <h:outputText value="#{photo.photoUser.userName}" />                            
                            </h2>
                            <p>
                                Real Name: <h:outputText value="#{photo.photoUser.realName}"/><br></br>
                                Location: <h:outputText value="#{photo.photoUser.location}"/>
                            </p>
                        </div>
                        <hr></hr>
                        <h4><h:outputText value="Recent Photos:"></h:outputText></h4>
                        
                        <ui:repeat  value="#{photo.photoUser.photos}" var="userPhoto" varStatus="status">
                            <a class="fancybox-thumb darken" rel="fancybox-thumb" href="#{userPhoto.url}" title="#{userPhoto.title}"> 
                                <img src="#{userPhoto.smallPhotoUrl}" />
                            </a> 
                        </ui:repeat>
                        
                        <hr></hr>
                        <h4><h:outputText value="People Contacts:"></h:outputText></h4>
                        <ui:repeat  value="#{photo.contacts}" var="contact" varStatus="status" rendered="#{not empty photo.contacts}">
                            <div class="contactInfo">
                                    <img class="contactIcon" src="#{contact.buddyIconUrl}"></img>
                                    <span>
                                        <h:outputText value="#{contact.userName}"/>                            
                                    </span>
                                </div>
                        </ui:repeat>
                        <div class="clear">
                            <p></p>
                        </div>
                        <h:outputText rendered="#{empty photo.contacts}" value="No Contacts"></h:outputText>
                        <p>
                            <a href="#{photo.photoUser.profileUrl}" target="_blank"><button class="button">Learn More...</button></a>
                        </p>
                        <div class="clear">
                            <p></p>
                        </div>
                    </div>
                </ui:repeat>
                
          </div>
                
            
             <div class="clear">
                <p></p>
            </div>
                
            <div id="footer">
                <p>Copyright &copy; Yingliang Zhang 2013</p>
            </div>
            
            </h:form>
        </div>
    
    
    </h:body>
</html>

web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Flickr Photo Box</title>
        <link rel="stylesheet" href="resources/css/jquery.fancybox.css" />
        <link rel="stylesheet" href="resources/css/jquery.fancybox-thumbs.css" />
        <link rel="stylesheet" href="resources/css/main.css" />
    </h:head>
    <h:body id="home">
        <div id="wrapper">
            <h:form>
                <div id="searchBox">
                    <h:inputText class="searchTextInput" id="searchInput" title="Enter your search query." value="#{indexController.searchQuery}" />
                    <h:commandButton class="button" value="Search">
                        <f:ajax execute="searchInput" render="searchContainer" onevent="darkenImages" />
                    </h:commandButton>
                </div>
            

            <div id="header">
                <h:link outcome="index"><img id="logo" src="resources/img/LOGO.png" alt="Flickr Photo Box" /></h:link>
                <div id="navbar">
                    <ul>
                        <li id="homeNav"><h:link styleClass="navLink" outcome="index">Home</h:link></li>
                        <li><h:link styleClass="navLink" outcome="places">Places</h:link></li>
                        <li><h:link styleClass="navLink" outcome="author">People</h:link></li>
                    </ul>
                </div>
            </div>
            
            <div class="clear">
                <p></p>
            </div>
          
          <!-- The image slider that displaying the top five recent photos, including their user icons and user names -->
          <div id="content">  
            <div id="slider">
                <h:outputText style="display: none;" value="#{indexController.recentPhotos}"></h:outputText>
                <div class="current topSlide">
                    <img class="slidePhoto" src="#{indexController.p1.url}"></img>
                    <div class="photoInfo">
                        <img src="#{indexController.p1.photoUser.buddyIconUrl}"></img>
                        <h3><h:outputText value="#{indexController.p1.photoUser.userName}" /></h3>
                    </div>
                </div>
                <div class="next">
                    <img class="slidePhoto" src="#{indexController.p2.url}"></img>
                    <div class="photoInfo">
                        <img src="#{indexController.p2.photoUser.buddyIconUrl}"></img>
                        <h3><h:outputText value="#{indexController.p2.photoUser.userName}" /></h3>
                    </div>
                </div>
                <div class="next">
                    <img class="slidePhoto" src="#{indexController.p3.url}"></img>
                    <div class="photoInfo">
                        <img src="#{indexController.p3.photoUser.buddyIconUrl}"></img>
                        <h3><h:outputText value="#{indexController.p3.photoUser.userName}" /></h3>
                    </div>
                </div>
                <div class="next">
                    <img class="slidePhoto" src="#{indexController.p4.url}"></img>
                    <div class="photoInfo">
                        <img src="#{indexController.p4.photoUser.buddyIconUrl}"></img>
                        <h3><h:outputText value="#{indexController.p4.photoUser.userName}" /></h3>
                    </div>
                </div>
                <div class="next">
                    <img class="slidePhoto" src="#{indexController.p5.url}"></img>
                    <div class="photoInfo">
                        <img src="#{indexController.p5.photoUser.buddyIconUrl}"></img>
                        <h3><h:outputText value="#{indexController.p5.photoUser.userName}" /></h3>
                    </div>
                </div>
            </div>
                
            <h:panelGroup id="searchContainer">
                <!-- Here we output a text value depending if we have photos via 'not empty' and if we do not via 'empty' -->
                <h:outputText value="Search for photos in the search field above." rendered="#{empty indexController.photos}" styleClass="searchHeading"/>
                <h:outputText value="Displaying search results..." rendered="#{not empty indexController.photos}" styleClass="searchHeading"/>
                <hr />
                <h:outputText value="#{indexController.searchPhotos}" style="display: none" />
                <ui:repeat id="searchResults" value="#{indexController.searchedPhotos}" var="photo" varStatus="status">
                    <section class="searchPhotos">
                        <a class="fancybox-thumb darken" rel="fancybox-thumb" href="#{photo.url}" title="#{photo.title}">
                            <img id="collectionPhoto" src="#{photo.mediumPhotoUrl}" />
                        </a>
                        <div id="collectionPhotoInfo">
                            <img id="collectionPhotoUserIcon" src="#{photo.photoUser.buddyIconUrl}"></img>
                            <span>
                                <b><h:outputText value="#{photo.title}" /></b>
                                <br></br>
                                <h:outputText value="#{photo.photoUser.userName}" />                            
                            </span>
                        </div>
                    </section>
                </ui:repeat>
            </h:panelGroup>
          
         </div> 
            
             <div class="clear">
                <p></p>
            </div>
                
            <div id="footer">
                <p>Copyright &copy; Yingliang Zhang 2013</p>
            </div>
            
            </h:form>
        </div>
        
    <script type="text/javascript" src="resources/js/jquery-1.10.2.js"></script>
    <script type="text/javascript" src="resources/js/jquery.fancybox.pack.js"></script>
    <script type="text/javascript" src="resources/js/main.js"></script>
    </h:body>
</html>

web/places.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Places</title>
        <link rel="stylesheet" href="resources/css/jquery.fancybox.css" />
        <link rel="stylesheet" href="resources/css/jquery.fancybox-thumbs.css" />
        <link rel="stylesheet" href="resources/css/main.css" />
        <script type="text/javascript" src="resources/js/jquery-1.10.2.js"></script>
        <script type="text/javascript" src="resources/js/jquery.fancybox.pack.js"></script>
        <script type="text/javascript" src="resources/js/main.js"></script>
    </h:head>
    <h:body id="places">
        <div id="wrapper">
            <h:form>
                <div id="searchBox">
                    <h:inputText class="searchTextInput" id="searchInput" title="Enter your search query." value="#{placesController.searchQuery}" />
                    <h:commandButton class="button" value="Search">
                        <f:ajax execute="searchInput" render="searchContainer" onevent="darkenImages" />
                    </h:commandButton>
                </div>
            
            <div id="header">
                <h:link outcome="index"><img id="logo" src="resources/img/LOGO.png" alt="Flickr Photo Box" /></h:link>
                <div id="navbar">
                    <ul>
                        <li><h:link styleClass="navLink" outcome="index">Home</h:link></li>
                        <li id="placesNav"><h:link styleClass="navLink" outcome="places">Places</h:link></li>
                        <li><h:link styleClass="navLink" outcome="author">People</h:link></li>
                    </ul>
                </div>
            </div>
            
            <div class="clear">
                <p></p>
            </div>

                
          <div id="content">
              <h:panelGroup id="searchContainer">
                <!-- Here we output a text value depending if we have photos via 'not empty' and if we do not via 'empty' -->
                <h:outputText style="display: none;" value="#{placesController.places}"></h:outputText>
                <hr />
                    <section>
                        <div>
                            <span> 
                                <h3><h:outputText style="font-weight: bold;" value="Location: " /><h:outputText value="#{placesController.place.content}" /></h3>
                                <span>Time Zone:<h:outputText value="#{placesController.place.timezone}" /></span>                            
                            </span>
                        </div>
                        <h:outputText value="Search for place and place photos in the search field above."/>
                        <hr></hr>
                        <h3><h:outputText value="Phtots taken around: #{placesController.place.content}" rendered="#{not empty placesController.place.photos}"/></h3>
                        <h:outputText value="#{placesController.place.placePhotos}" style="display: none" />
                        <ui:repeat value="#{placesController.place.photos}" var="photo" varStatus="status" rendered="#{not empty placesController.place.photos}">
                            <a class="fancybox-thumb darken" rel="fancybox-thumb" href="#{photo.url}" title="#{photo.title}">
                                <img src="#{photo.smallPhotoUrl}"></img>
                            </a>
                        </ui:repeat>
                    </section>
            </h:panelGroup>
                
          </div>
                
            
             <div class="clear">
                <p></p>
            </div>
                
            <div id="footer">
                <p>Copyright &copy; Yingliang Zhang 2013</p>
            </div>
            
            </h:form>
        </div>
    </h:body>
</html>